### ISSUE TITLE
How to train this model qformer?

### ISSUE THREAD

**Issue by leedaehan-kev** [kyegomez/qformer#4]
Hello!

Thank you very much for your work on implementing qformer!

I am interested in training qformer and was wondering if there are any plans to release the code?

Thank you.

**Comment by qingxinxia** [comment]
Hi, did you solved this problem? I'm also very interested in qformer, could you tell me how to use it? Thanks a lot!

**Comment by leedaehan-kev** [comment]
@qingxinxia 

 No, I have not explored anything specifically related to qformer after leaving this question. I apologize for not being able to help.
